<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSGN.Application\PSGN.Application.csproj" />
    <ProjectReference Include="..\PSGN.Domain\PSGN.Domain.csproj" />
    <ProjectReference Include="..\PSGN.Infra\PSGN.Infra.csproj" />
  </ItemGroup>

</Project>
