// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSGN.Infra.Data;

#nullable disable

namespace PSGN.Infra.Migrations
{
    [DbContext(typeof(PSGNDbContext))]
    [Migration("20261007200553_primeira_migration")]
    partial class primeira_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSGN.Domain.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAluno"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Egresso")
                        .HasColumnType("bit");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdAluno");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("PSGN.Domain.AlunoModulo", b =>
                {
                    b.Property<int>("IdAlunoModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlunoModulo"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdAlunoModulo");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdModulo");

                    b.ToTable("AlunosModulos");
                });

            modelBuilder.Entity("PSGN.Domain.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCoordenador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerLetivo")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdCurso");

                    b.HasIndex("IdCoordenador");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PSGN.Domain.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCmidMoodle")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<string>("IdnumberMoodle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdModulo");

                    b.HasIndex("IdCurso");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("PSGN.Domain.ProfessorModulo", b =>
                {
                    b.Property<int>("IdProfessorModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfessorModulo"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("ModuloIdModulo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdProfessorModulo");

                    b.HasIndex("IdModulo");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("ModuloIdModulo");

                    b.ToTable("ProfessoresModulos");
                });

            modelBuilder.Entity("PSGN.Domain.Tentativa", b =>
                {
                    b.Property<int>("IdTentativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTentativa"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFimAttempt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFimTentativa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioAttempt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioTentativa")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAlunoModulo")
                        .HasColumnType("int");

                    b.Property<int>("IdAttempt")
                        .HasColumnType("int");

                    b.Property<double?>("Nota")
                        .HasColumnType("float");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Prazo")
                        .HasColumnType("time");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdTentativa");

                    b.HasIndex("IdAlunoModulo");

                    b.ToTable("Tentativas");
                });

            modelBuilder.Entity("PSGN.Domain.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PSGN.Domain.Aluno", b =>
                {
                    b.HasOne("PSGN.Domain.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSGN.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PSGN.Domain.AlunoModulo", b =>
                {
                    b.HasOne("PSGN.Domain.Aluno", "Aluno")
                        .WithMany("Modulos")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSGN.Domain.Modulo", "Modulo")
                        .WithMany("Alunos")
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("PSGN.Domain.Curso", b =>
                {
                    b.HasOne("PSGN.Domain.Usuario", "Coordenador")
                        .WithMany()
                        .HasForeignKey("IdCoordenador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordenador");
                });

            modelBuilder.Entity("PSGN.Domain.Modulo", b =>
                {
                    b.HasOne("PSGN.Domain.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("PSGN.Domain.ProfessorModulo", b =>
                {
                    b.HasOne("PSGN.Domain.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSGN.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSGN.Domain.Modulo", null)
                        .WithMany("Professores")
                        .HasForeignKey("ModuloIdModulo");

                    b.Navigation("Modulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PSGN.Domain.Tentativa", b =>
                {
                    b.HasOne("PSGN.Domain.AlunoModulo", "AlunoModulo")
                        .WithMany("Tentativas")
                        .HasForeignKey("IdAlunoModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlunoModulo");
                });

            modelBuilder.Entity("PSGN.Domain.Aluno", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("PSGN.Domain.AlunoModulo", b =>
                {
                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("PSGN.Domain.Curso", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("PSGN.Domain.Modulo", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Professores");
                });
#pragma warning restore 612, 618
        }
    }
}
